Team-return/JOBIS-ANDROID-V2

- app/build.gradle.kts
- app/src/main/java/team/retum/jobisandroidv2/JobisApp.kt
- app/src/main/java/team/retum/jobisandroidv2/MainActivity.kt
- app/src/main/java/team/retum/jobisandroidv2/navigation/AuthNavigation.kt
- app/src/main/java/team/retum/jobisandroidv2/navigation/HomeNavigation.kt
- app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
- gradle/libs.versions.toml
navigation을 세팅했습니다.
- JobisApp 구현
- Auth/Main/Home Navigation 구현
> 없음
> Setting navigation

- app/src/main/java/team/retum/jobisandroidv2/navigation/AuthNavigation.kt
- feature/signup/src/main/java/team/retum/signup/navigation/SetProfileNavigation.kt
- feature/signup/src/main/java/team/retum/signup/navigation/SignUpNavigation.kt
- feature/signup/src/main/java/team/retum/signup/navigation/TermsNavigation.kt
- feature/signup/src/main/java/team/retum/signup/ui/SetProfileScreen.kt
- feature/signup/src/main/java/team/retum/signup/ui/TermsScreen.kt
- feature/signup/src/main/res/values/strings.xml
약관 동의 스크린을 퍼블리싱 했습니다.
- 웹뷰 연동
- 내비게이션 구현
> 없음
> 🔗 :: (#51) 약관 동의 스크린 퍼블리싱

- app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
- core/data/src/main/java/team/retum/data/di/RepositoryModule.kt
- core/data/src/main/java/team/retum/data/repository/BookmarkRepository.kt
- core/data/src/main/java/team/retum/data/repository/BookmarkRepositoryImpl.kt
- core/domain/src/main/java/team/retum/usecase/entity/BookmarksEntity.kt
- core/domain/src/main/java/team/retum/usecase/usecase/bookmark/BookmarkRecruitmentUseCase.kt
- core/domain/src/main/java/team/retum/usecase/usecase/bookmark/BookmarkUseCase.kt
- core/domain/src/main/java/team/retum/usecase/usecase/bookmark/RecruitmentBookmarkUseCase.kt
- core/domain/src/main/java/team/retum/usecase/usecase/user/SignInUseCase.kt
- core/network/build.gradle.kts
- core/network/src/main/java/team/retum/network/api/BookmarkApi.kt
- core/network/src/main/java/team/retum/network/datasource/BookmarkDataSource.kt
- core/network/src/main/java/team/retum/network/datasource/BookmarkDataSourceImpl.kt
- core/network/src/main/java/team/retum/network/di/DataSourceModule.kt
- core/network/src/main/java/team/retum/network/di/NetworkModule.kt
- core/network/src/main/java/team/retum/network/model/response/BookmarksResponse.kt
- core/network/src/main/java/team/retum/network/util/TokenInterceptor.kt
- feature/bookmark/build.gradle.kts
- feature/bookmark/src/main/java/team/retum/bookmark/navigation/BookmarkNavigation.kt
- feature/bookmark/src/main/java/team/retum/bookmark/ui/BookmarkScreen.kt
- feature/bookmark/src/main/java/team/retum/bookmark/viewmodel/BookmarkViewModel.kt
- feature/signin/src/main/java/team/retum/signin/viewmodel/SignInViewModel.kt
- gradle/libs.versions.toml
- 북마크 기능 구현
- 모집의뢰서로 네비게이션 구현
- okhttp로거 추가
- entity 추가
> 없음
> 🔗 :: (#43) 북마크 서버 연동

- app/src/main/java/team/retum/jobisandroidv2/ApplicationNavigation.kt
- app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
- app/src/main/java/team/retum/jobisandroidv2/ui/ApplicationScreen.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/navigation/RecruitmentDetailsNavigation.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
지원하기 화면을 퍼블리싱 했습니다.
- ApplicationNavigation 구현
- ApplicationScreen 구현
> 없음
> 🔗 :: (#72) 지원하기 퍼블리싱

- app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
- app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
빌드 오류를 수정했습니다.
- onBackPressed 파라미터 추가
> 없음
> 🔗 :: (#86) 빌드 오류 수정

- .editorconfig
- .github/workflows/android.yml
- app/build.gradle.kts
- app/src/main/java/team/retum/jobisandroidv2/ui/JobisApp.kt
- build.gradle.kts
- gradle/libs.versions.toml
ktlint ci를 설정하였습니다.
- editorconfig 추가
> 없음
> 🔗 :: (#88) ktlint 자동화

- core/common/src/main/java/team/retum/common/component/Skills.kt
- core/common/src/main/java/team/retum/common/enums/ReviewProcess.kt
- core/design-system/src/main/java/team/retum/jobisdesignsystemv2/checkbox/CheckBox.kt
- feature/mypage/src/main/java/team/returm/mypage/viewmodel/MyPageViewModel.kt
- feature/review/src/main/java/team/retum/review/ui/PostReviewScreen.kt
- feature/review/src/main/java/team/retum/review/viewmodel/ReviewViewModel.kt
- feature/review/src/main/res/values/strings.xml
> 🔗 :: (104) 후기 재구현

- feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
- feature/home/src/main/res/values/strings.xml
> 🔗 :: (#103) 홈 화면 체험형 현장실습 기능 구현

- core/common/src/main/java/team/retum/common/component/Skills.kt
- feature/interests/src/main/java/team/retum/jobis/interests/ui/InterestsScreen.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentFilterScreen.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentsScreen.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/viewmodel/RecruitmentFilterViewModel.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/viewmodel/RecruitmentsViewModel.kt
- feature/recruitment/src/main/res/values/strings.xml
> 🔗 :: (#109) 모집의뢰서 필터

- app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
- core/common/src/main/java/team/retum/common/component/ReviewContent.kt
- core/common/src/main/java/team/retum/common/utils/ResourceKeys.kt
- core/domain/src/main/java/team/retum/usecase/entity/FetchReviewsEntity.kt
- feature/company/build.gradle.kts
- feature/company/src/main/java/team/retum/company/navigation/CompanyDetailsNavigation.kt
- feature/company/src/main/java/team/retum/company/ui/CompanyDetailsScreen.kt
- feature/company/src/main/java/team/retum/company/viewmodel/CompanyDetailsViewModel.kt
- feature/company/src/main/res/values/strings.xml
- feature/review/build.gradle.kts
- feature/review/src/main/java/team/retum/review/navigation/ReviewDetailsNavigation.kt
- feature/review/src/main/java/team/retum/review/navigation/ReviewsNavigation.kt
- feature/review/src/main/java/team/retum/review/ui/PostReviewScreen.kt
- feature/review/src/main/java/team/retum/review/ui/ReviewDetailsScreen.kt
- feature/review/src/main/java/team/retum/review/ui/ReviewsScreen.kt
- feature/review/src/main/java/team/retum/review/viewmodel/ReviewDetailsViewModel.kt
- feature/review/src/main/java/team/retum/review/viewmodel/ReviewsViewModel.kt
- feature/review/src/main/res/values/strings.xml
면접 후기 조회 기능을 구현했습니다.
- ReviewsScreen 구현
- ReviewsViewModel 구현
> 없음
> 🔗 :: (#106) 면접후기 조회 구현

- core/data/src/main/java/team/retum/data/repository/notice/NoticeRepository.kt
- core/data/src/main/java/team/retum/data/repository/notice/NoticeRepositoryImpl.kt
- core/domain/src/main/java/team/retum/usecase/entity/notice/NoticeDetailsEntity.kt
- core/domain/src/main/java/team/retum/usecase/usecase/notice/FetchNoticeDetailsUseCase.kt
- core/network/src/main/java/team/retum/network/api/NoticeApi.kt
- core/network/src/main/java/team/retum/network/datasource/notice/NoticeDataSource.kt
- core/network/src/main/java/team/retum/network/datasource/notice/NoticeDataSourceImpl.kt
- core/network/src/main/java/team/retum/network/di/RequestUrls.kt
- core/network/src/main/java/team/retum/network/model/response/notice/FetchNoticeDetailsResponse.kt
- feature/notice/src/main/java/team/retum/jobis/notice/navigation/NoticeDetailsNavigation.kt
- feature/notice/src/main/java/team/retum/jobis/notice/ui/NoticeDetailsScreen.kt
- feature/notice/src/main/java/team/retum/jobis/notice/viewmodel/NoticeDetailsViewModel.kt
공지사항 상세를 기능 개발합니다.
- 
> 스크린 아직 안나와서 이상할 수도 있어요
> 🔗 :: (#115) 공지사항 상세 기능 구현

- app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
- app/src/main/java/team/retum/jobisandroidv2/root/RootNavigation.kt
- app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
- core/common/src/main/java/team/retum/common/model/ReApplyData.kt
- core/domain/src/main/java/team/retum/usecase/entity/application/AppliedCompaniesEntity.kt
- core/network/src/main/java/team/retum/network/model/response/application/FetchAppliedCompaniesResponse.kt
- feature/application/src/main/java/team/retum/jobis/application/navigation/ApplicationNavigation.kt
- feature/home/src/main/java/team/retum/home/navigation/HomeNavigation.kt
- feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
- feature/home/src/main/java/team/retum/home/viewmodel/HomeViewModel.kt
- feature/home/src/main/res/values/strings.xml
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/navigation/RecruitmentDetailsNavigation.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
홈 화면 미구현 기능을 구현했습니다.
- 배너 기능 주석처리
- 회사 로고 url 옵셔널 제거
- 재지원 내비게이션 기능 구현
> 없음
> 🔗 :: (#119) 홈 화면 미구현 기능 구현

- core/design-system/src/main/java/team/retum/jobisdesignsystemv2/tab/TabBar.kt
- feature/notification/src/main/java/team/retum/notification/viewmodel/NotificationsViewModel.kt
> 🔗 :: (#129) tab bar 리컴포지션 최적화

- app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
- app/src/main/java/team/retum/jobisandroidv2/ui/BottomMenu.kt
- core/data/src/main/java/team/retum/data/repository/student/StudentRepository.kt
- core/data/src/main/java/team/retum/data/repository/student/StudentRepositoryImpl.kt
- core/domain/src/main/java/team/retum/usecase/usecase/student/EditProfileImageUseCase.kt
- core/network/src/main/java/team/retum/network/api/StudentApi.kt
- core/network/src/main/java/team/retum/network/datasource/student/RemoteStudentDataSource.kt
- core/network/src/main/java/team/retum/network/datasource/student/RemoteStudentDataSourceImpl.kt
- core/network/src/main/java/team/retum/network/model/request/student/EditProfileImageRequest.kt
- feature/mypage/src/main/java/team/retum/jobis/ui/MyPageScreen.kt
- feature/mypage/src/main/java/team/retum/jobis/viewmodel/MyPageViewModel.kt
- feature/mypage/src/main/res/values/strings.xml
유저 프로필 사진 변경 기능을 구현했습니다.
- EditProfileImageUseCase 작성
- 유저 프로필 수정 비즈니스 로직 작성
> 없음
> 🔗 :: (#127) 유저 프로필 사진 변경 기능 구현

- app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
- feature/company/src/main/java/team/retum/company/navigation/SearchCompaniesNavigation.kt
- feature/company/src/main/java/team/retum/company/ui/CompaniesScreen.kt
- feature/company/src/main/java/team/retum/company/ui/SearchCompaniesScreen.kt
- feature/company/src/main/java/team/retum/company/viewmodel/CompanyViewModel.kt
- feature/company/src/main/res/values/strings.xml
- feature/notice/src/main/java/team/retum/jobis/notice/ui/NoticeDetailsScreen.kt
- feature/notice/src/main/java/team/retum/jobis/notice/viewmodel/NoticesViewModel.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentFilterScreen.kt
- feature/review/src/main/java/team/retum/review/ui/PostReviewScreen.kt
- 검색에서 상세페이지로 이동할 수 있도록 함
- 검색 요청량 감소
- 예외처리
> 없음
> 🔗 :: (#136) 기업검색 상세

- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
> 🔗 :: (#132) 모집의뢰서 상세 데이터 수정

- core/domain/src/main/java/team/retum/usecase/entity/notice/NoticesEntity.kt
- core/network/src/main/java/team/retum/network/model/response/notice/FetchNoticeDetailsResponse.kt
- core/network/src/main/java/team/retum/network/model/response/notice/FetchNoticesResponse.kt
- feature/notice/src/main/java/team/retum/jobis/notice/navigation/NoticeDetailsNavigation.kt
- feature/notice/src/main/java/team/retum/jobis/notice/ui/NoticeDetailsScreen.kt
- feature/notice/src/main/java/team/retum/jobis/notice/ui/NoticesScreen.kt
- feature/notice/src/main/java/team/retum/jobis/notice/viewmodel/NoticeDetailsViewModel.kt
- feature/notice/src/main/res/values/string.xml
> 🔗 :: (#135) 공지사항 상세 네비게이션 수정

- app/build.gradle.kts
- app/src/main/java/team/retum/jobisandroidv2/MainActivity.kt
- app/src/main/res/values-night/themes.xml
- app/src/main/res/values/themes.xml
- gradle/libs.versions.toml
인 앱 업데이트 기능 구현
- google app service 의존성 추가
> 배포합시다
> 🔗 :: (#142) 인 앱 업데이트 기능 구현

- app/build.gradle.kts
- app/src/main/java/team/retum/jobisandroidv2/MainActivity.kt
- app/src/main/java/team/retum/jobisandroidv2/ui/BottomNavigationBar.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/SearchRecruitmentScreen.kt
- gradle/libs.versions.toml
- anr 시간 연장 5->10초
- 모집의뢰서 빈화면 보여주기
- 바텀네비게이션 중복 클릭 제한
> 없음
> 🔗 :: (#154)  anr 버그

- app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
- core/common/src/main/java/team/retum/common/utils/ResourceKeys.kt
- core/domain/src/main/java/team/retum/usecase/entity/RecruitmentDetailsEntity.kt
- core/domain/src/main/java/team/retum/usecase/entity/company/CompanyDetailsEntity.kt
- core/domain/src/main/java/team/retum/usecase/usecase/recruitment/FetchRecruitmentDetailsUseCase.kt
- feature/company/src/main/java/team/retum/company/navigation/CompanyDetailsNavigation.kt
- feature/company/src/main/java/team/retum/company/ui/CompanyDetailsScreen.kt
- feature/company/src/main/java/team/retum/company/viewmodel/CompanyDetailsViewModel.kt
- feature/company/src/main/res/values/strings.xml
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/navigation/RecruitmentDetailsNavigation.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/viewmodel/RecruitmentDetailsViewModel.kt
모집의뢰서 상세, 기업 상세에서 중복 이동이 되는 현상을 방지했습니다
- isMovedRecruitmentDetails 변수 추가
- isMovedCompanyDetails 변수 추가
> 없음
> 🔗 :: (#143) 기업 상세 모집의뢰서 상세 내비게이션 기능 구현

- app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
- app/src/main/java/team/retum/jobisandroidv2/root/RootNavigation.kt
- app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
- core/common/src/main/java/team/retum/common/enums/AlarmType.kt
- core/domain/src/main/java/team/retum/usecase/entity/notification/NotificationsEntity.kt
- core/network/src/main/java/team/retum/network/model/response/notification/FetchNotificationsResponse.kt
- feature/application/src/main/java/team/retum/jobis/application/ui/ApplicationScreen.kt
- feature/home/src/main/java/team/retum/home/navigation/HomeNavigation.kt
- feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
- feature/home/src/main/java/team/retum/home/viewmodel/HomeViewModel.kt
- feature/notification/build.gradle.kts
- feature/notification/src/main/java/team/retum/notification/di/TokenManagerModule.kt
- feature/notification/src/main/java/team/retum/notification/model/NotificationDetailData.kt
- feature/notification/src/main/java/team/retum/notification/navigation/NotificationsNavigation.kt
- feature/notification/src/main/java/team/retum/notification/ui/NotificationsScreen.kt
- feature/notification/src/main/java/team/retum/notification/viewmodel/NotificationsViewModel.kt
notificationId 버그를 수정 합니다
- 알림 리스트에서 클릭 처리
- 홈 화면 스크롤 및 효과 추가
> 없음
> 🔗 :: (#148) notificationid 버그

- core/domain/src/main/java/team/retum/usecase/entity/notice/NoticeDetailsEntity.kt
- core/domain/src/main/java/team/retum/usecase/entity/notice/NoticesEntity.kt
> 🔗 :: (#165) 공지사항 날짜 변경

- app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
- feature/bookmark/src/main/java/team/retum/bookmark/navigation/BookmarkNavigation.kt
- feature/bookmark/src/main/java/team/retum/bookmark/ui/BookmarkScreen.kt
- feature/bookmark/src/main/java/team/retum/bookmark/viewmodel/BookmarkViewModel.kt
- feature/bookmark/src/main/res/values/strings.xml
> 🔗 :: (#144) 상세로 이동

- core/domain/src/main/java/team/retum/usecase/entity/FetchReviewsEntity.kt
- feature/review/src/main/java/team/retum/review/ui/ReviewDetailsScreen.kt
> 🔗 :: (#171) 면접 후기 상세 버그

- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
모집의뢰서 상세 포지션 클릭 효과를 변경합니다
- 
> 없음
> 🔗 :: (#145) 모집의뢰서 상세 포지션 클릭 효과 변경

- core/domain/src/main/java/team/retum/usecase/entity/RecruitmentDetailsEntity.kt
- core/network/src/main/java/team/retum/network/model/response/FetchRecruitmentDetailsResponse.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
> 🔗 :: (#177) 모집의뢰서 상세 데이터 수정

- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentsScreen.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/component/RecruitmentContent.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/viewmodel/RecruitmentsViewModel.kt
> 🔗 :: (#181) 필터 고치기

- app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
- app/src/main/java/team/retum/jobisandroidv2/root/RootNavigation.kt
- app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
- feature/home/src/main/java/team/retum/home/navigation/HomeNavigation.kt
- feature/home/src/main/java/team/retum/home/ui/ApplyCompanyItem.kt
- feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
- feature/home/src/main/java/team/retum/home/viewmodel/HomeViewModel.kt
- feature/home/src/main/res/values/strings.xml
지원 내역 클릭 시 모집의뢰서 상세 조회 화면으로 이동하는 기능을 구현했습니다.
- 알림 스크롤 애니메이션 로직 수정
> 없음
> 🔗 :: (#146) 지원 내역 클릭 시 모집의뢰서 상세 조회 기능 구현

- app/src/main/java/team/retum/jobisandroidv2/root/RootNavigation.kt
- app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
- core/common/build.gradle.kts
- core/common/src/main/java/team/retum/common/model/ApplicationData.kt
- core/common/src/main/java/team/retum/common/model/ReApplyData.kt
- core/data/src/main/java/team/retum/data/repository/application/ApplicationRepository.kt
- core/data/src/main/java/team/retum/data/repository/application/ApplicationRepositoryImpl.kt
- core/domain/src/main/java/team/retum/usecase/usecase/application/ReApplyCompanyUseCase.kt
- core/network/src/main/java/team/retum/network/api/ApplicationApi.kt
- core/network/src/main/java/team/retum/network/datasource/application/RemoteApplicationDataSource.kt
- core/network/src/main/java/team/retum/network/datasource/application/RemoteApplicationDataSourceImpl.kt
- feature/application/src/main/java/team/retum/jobis/application/model/CompanyInfo.kt
- feature/application/src/main/java/team/retum/jobis/application/navigation/ApplicationNavigation.kt
- feature/application/src/main/java/team/retum/jobis/application/ui/ApplicationScreen.kt
- feature/application/src/main/java/team/retum/jobis/application/viewmodel/ApplicationViewModel.kt
- feature/application/src/main/res/values/strings.xml
- feature/home/src/main/java/team/retum/home/navigation/HomeNavigation.kt
- feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
- feature/home/src/main/java/team/retum/home/viewmodel/HomeViewModel.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/navigation/RecruitmentDetailsNavigation.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
재지원 api를 연동했습니다.
- ApplicationScreen argument 정리
- reApply api 연동
> 없음
> 🔗 :: (#149) 재지원하기 api 연결

- app/src/main/java/team/retum/jobisandroidv2/MainActivity.kt
- app/src/main/res/values-night/themes.xml
- buildSrc/src/main/kotlin/ProjectProperties.kt
1.0.1 배포를 진행합니다.
- 다크모드 비활성화 (다크모드 수정사항이 많아서 일단 비활성화 처리해두었어요)
- 버전업
> 없음
> 🔗 :: (#189) 1.0.1 배포

- app/src/main/java/team/retum/jobisandroidv2/root/RootNavigation.kt
- app/src/main/java/team/retum/jobisandroidv2/ui/BottomNavigationBar.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/component/RecruitmentContent.kt
연봉 정보 삭제
- 연봉 정보 삭제
- 네비게이션 수정
> 없음
> 🔗 :: (#183) 연봉 정보 삭제

- feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
- feature/home/src/main/java/team/retum/home/viewmodel/HomeViewModel.kt
홈 화면 취업률 로직을 수정했습니다.
- 기수 계산 로직 추가
- 취업률 Long -> Float 로 변경
> 없음
> 🔗 :: (#193) 홈 화면 취업률 수정

- buildSrc/src/main/kotlin/ProjectProperties.kt
- feature/home/src/main/java/team/retum/home/ui/ApplyCompanyItem.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
- feature/review/src/main/java/team/retum/review/ui/ReviewDetailsScreen.kt
카드 클릭 이벤트를 수정했습니다.
- 홈 화면 지원 내역 화살표 수정
- 모집의뢰서 상세 포지션 상세 카드 이벤트 수정
- 리뷰 상세 포지션 카드 수정
> 없음
> 🔗 :: (#195) 카드 클릭 이벤트 수정

- feature/recruitment/src/main/res/values/strings.xml
텍스트 오타 수정
- 3학년만 지원할 수 있어요 텍스트 오타를 수정했습니다.
> 없음
> 🔗 :: (#199) 텍스트 오타 수정

- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentsScreen.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/viewmodel/RecruitmentsViewModel.kt
- feature/review/src/main/java/team/retum/review/ui/PostReviewScreen.kt
필터 페이징 이슈 해결
- 필터 적용 시 페이지 1로 초기화
> 없음
> 🔗 :: (#204) 필터 페이징 이슈

- app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
- app/src/main/java/team/retum/jobisandroidv2/ui/JobisApp.kt
- buildSrc/src/main/kotlin/ProjectProperties.kt
바텀 내비게이션 애니메이션을 설정했습니다.
- dark mode 섬광탄 해결
- 내비게이션 애니메이션 설정
> 없음
> 🔗 :: (#207) 바텀 내비게이션 애니메이션 설정

- feature/home/src/main/java/team/retum/home/viewmodel/HomeViewModel.kt
list 타입을 변경했습니다.
- HomeViewModel appliedCompanies mutableList -> SnapshotStateList로 변경
> 없음
> 🔗 :: (#211) list 타입 변경

- core/network/src/main/java/team/retum/network/di/NetworkModule.kt
- core/network/src/main/java/team/retum/network/util/TokenAuthenticator.kt
- core/network/src/main/java/team/retum/network/util/TokenInterceptor.kt
토큰 리프레시 기능을 구현했습니다.
- TokenAuthenticator 구현
- TokenInterceptor accessToken 로컬 변수에서 필드로 변경
> 없음
> 🔗 :: (#213) 토큰 리프레시 구현

- core/design-system/src/main/java/team/retum/jobisdesignsystemv2/foundation/JobisColor.kt
- feature/mypage/src/main/java/team/retum/jobis/ui/MyPageScreen.kt
컬러 팔레트를 수정했습니다.
- Light primary 컬러 수정
- Dark primary 컬러 수정
> 없음
> 🔗 :: (#220) 컬러 팔레트 수정

- core/domain/src/main/java/team/retum/usecase/entity/CompaniesEntity.kt
- feature/company/src/main/java/team/retum/company/component/CompanyItem.kt
- feature/company/src/main/java/team/retum/company/ui/CompaniesScreen.kt
- feature/company/src/main/java/team/retum/company/viewmodel/CompaniesViewModel.kt
기업 리스트 스켈레톤 효과를 적용했습니다.
- 페이징 로직 개선
- 스켈레톤 효과 추가
> 없음
> 🔗 :: (#222) 기업 리스트 스켈레톤 처리

- core/common/src/main/java/team/retum/common/enums/MilitarySupport.kt
- core/domain/src/main/java/team/retum/usecase/entity/RecruitmentsEntity.kt
- feature/company/src/main/java/team/retum/company/component/CompanyItem.kt
- feature/company/src/main/java/team/retum/company/component/CompanyItems.kt
- feature/company/src/main/java/team/retum/company/ui/CompaniesScreen.kt
- feature/company/src/main/java/team/retum/company/ui/SearchCompaniesScreen.kt
- feature/company/src/main/java/team/retum/company/viewmodel/CompaniesViewModel.kt
- feature/company/src/main/res/values/strings.xml
- feature/recruitment/build.gradle.kts
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentsScreen.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/SearchRecruitmentScreen.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/component/RecruitmentItems.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/viewmodel/RecruitmentsViewModel.kt
- feature/recruitment/src/main/res/values/strings.xml
모집의뢰서 페이징 로직을 리팩토링 했습니다.
- 모집의뢰서 페이징 로직 리팩토링
- 모집의뢰서 스켈레톤 효과 적용
> 없음
> 🔗 :: (#225) 모집의뢰서 페이징 리팩토링

- core/common/src/main/java/team/retum/common/utils/ComposableLifecycle.kt
- 컴포즈 함수의 소멸 시기, 현재 상태를 확인할 수 있게 해줌
> 없음
> 🔗 :: (#229) 컴포즈 함수 수명주기 테스트

- feature/signup/src/main/java/team/retum/signup/model/SignUpData.kt
- feature/signup/src/main/java/team/retum/signup/viewmodel/SetPasswordViewModel.kt
- feature/signup/src/main/java/team/retum/signup/viewmodel/SetProfileViewModel.kt
- feature/signup/src/main/java/team/retum/signup/viewmodel/TermsViewModel.kt
회원가입 시 비밀번호 특수문자가 JsonString으로 입력되면 JsonDecodingException이 발생하는 오류를 수정했습니다.
- password Json Encoding/Decoding 적용
- image url JsonEncoding/Decoding 적용
> 없음
> 🔗 :: (#233) 회원가입 jsondecodingexception 수정

- feature/change-password/src/main/java/team/retum/jobis/change/password/ui/ComparePasswordScreen.kt
- feature/change-password/src/main/java/team/retum/jobis/change/password/ui/ResetPasswordScreen.kt
- feature/change-password/src/main/java/team/retum/jobis/change/password/viewmodel/ComparePasswordViewModel.kt
- feature/change-password/src/main/res/values/strings.xml
- feature/signup/src/main/res/values/strings.xml
> 🔗 :: (#223) 비밀번호 특수문자 예시 적용

- buildSrc/src/main/kotlin/ProjectProperties.kt
- feature/home/src/main/java/team/retum/home/ui/ApplyCompanyItem.kt
- feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
- feature/signup/src/main/java/team/retum/signup/navigation/InputEmailNavigation.kt
- feature/signup/src/main/java/team/retum/signup/navigation/SelectGenderNavigation.kt
- feature/signup/src/main/java/team/retum/signup/navigation/SetPasswordNavigation.kt
- feature/signup/src/main/java/team/retum/signup/navigation/SetProfileNavigation.kt
- feature/signup/src/main/java/team/retum/signup/navigation/TermsNavigation.kt
Home -> ApplicationScreen 사이의 company logo url을 인코딩 했습니다.
- ApplicationData companyLogoUrl encoding/decoding
> 없음
> 🔗 :: (#235) url encoding

- .github/CODEOWNERS
- buildSrc/src/main/kotlin/ProjectProperties.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/component/RecruitmentItems.kt
북마크 아이콘 색상을 변경했습니다.
- 모집의뢰서 리스트에서 북마크 비활성화 아이콘 색 변경
- 모집의뢰서 상세에서 북마크 비활성화 아이콘 색 변경
> 없음
> 🔗 :: (#231) 북마크 아이콘 색상 변경

- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
- feature/recruitment/src/main/res/values/strings.xml
> 🔗 :: (#232) 지원 불가능 텍스트 변경

- settings.gradle.kts
project rebuild시 발생하는 오류를 수정했습니다.
- buildSrc task 스킵
> 없음
> 🔗 :: (#250) 빌드 오류 수정

- .github/workflows/android-ci.yml
- app/build.gradle.kts
- core/design-system/src/main/java/team/retum/jobisdesignsystemv2/tab/TabBar.kt
- gradle.properties
ci 속도를 줄이기 위해 최적화를 진행합니다.
- aradle properties caching 옵션 추가
- ci 파일 이름 변경
> ci 돌아가는걸 봐야해서 draft 상태로 계속 열어두겠습니다.
> 🔗 :: (#246) ci 최적화

- buildSrc/src/main/kotlin/CommonGradlePlugin.kt
- buildSrc/src/main/kotlin/ComposeGradlePlugin.kt
- buildSrc/src/main/kotlin/GradlePluginExtensions.kt
- core/common/src/main/java/team/retum/common/HiltTestRunner.kt
- gradle/libs.versions.toml
테스트 환경을 세팅했습니다.
- HiltTestRunner 추가
- 각종 test 의존성 추가
> 없음
> 🔗 :: (#252) 테스트 환경 세팅

- core/common/src/main/java/team/retum/common/utils/ResourceKeys.kt
- core/local/build.gradle.kts
- core/local/src/main/java/team/retum/jobis/local/database/JobisDatabase.kt
- core/local/src/main/java/team/retum/jobis/local/di/DatabaseModule.kt
- core/local/src/main/java/team/retum/jobis/local/entity/TestEntity.kt
- gradle/libs.versions.toml
Room 데이터베이스를 설정했어요
- Room dependency 추가
- JobisDatabase 구현
- Database 의존성 주입 로직 구현
> 없음
> 🔗 :: (#217) room 세팅

- buildSrc/src/main/kotlin/ProjectProperties.kt
- core/network/src/main/java/team/retum/network/util/TokenInterceptor.kt
로그인 액세스 토큰 초기화 버그를 수정했습니다.
- TokenIntercpetor accessToken 초기화 시점 변경
> 없음
> 🔗 :: (#257) 로그인 액세스 토큰 초기화 버그

- core/domain/src/main/java/team/retum/usecase/entity/CompaniesEntity.kt
- feature/company/src/main/java/team/retum/company/component/CompanyItems.kt
- 소수점이 0인경우 표기되지 않도록 코드를 수정했습니다.
> 없음
> 🔗 :: (#259) 소수점 포맷 수정

- app/src/main/java/team/retum/jobisandroidv2/ui/BottomNavigationBar.kt
- feature/company/src/main/java/team/retum/company/component/CompanyItems.kt
- feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
- feature/home/src/main/java/team/retum/home/viewmodel/HomeViewModel.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/component/RecruitmentItems.kt
뷰가 그려지기 전에 있는 딜레이를 감소시킨다
- 리스트 컴포지션 개선
- 중복해서 그리는 뷰 감소
> 없음
> 🔗 :: (#263) UI draw 속도 개선

- app/build.gradle.kts
- feature/home/src/main/java/team/retum/home/ui/HomeScreen.kt
- feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/RecruitmentDetailsScreen.kt
- feature/review/src/main/java/team/retum/review/ui/PostReviewScreen.kt
- feature/review/src/main/java/team/retum/review/ui/ReviewDetailsScreen.kt
- feature/signin/src/main/java/team/retum/signin/ui/SignInScreen.kt
- 빌드 최적화
- 최신 기술 사용
- 오래된 코드 변경
> 없음
> 🔗 :: (#266) 최신 코드로 개선

- core/common/src/main/java/team/retum/common/utils/ResourceKeys.kt
> 🔗 :: (#295) s3 url 변경

- app/build.gradle.kts
> 🚀 :: v2.1.2

- feature/mypage/src/main/java/team/retum/jobis/viewmodel/MyPageViewModel.kt
프로필 수정에 예외처리를 추가하였습니다.
- 
> 없음
> 🔗 :: (#428) 프로필 수정 예외처리
